追加:サービステーブルと中間テーブルを作成
O-H-K-N/tokyo-library-rails pull request #6
Opened 2022-08-22 03:40 UTC by isakashiori

## 実装内容

* 追加:サービステーブルと中間テーブルを作成　https://github.com/O-H-K-N/tokyo-library-rails/commit/a53677608b869f2c34571ec47525a744b1aa116d

2022-08-22 03:44 UTC, isakashiori commented
お疲れ様です！
内容確認お願いいたします。
また、中間テーブルとの紐付けのための設定である`has_many through`の記述を
libraryテーブルの方には追加しておりません....

2022-08-22 13:27 UTC, O-H-K-N requested changes
@isakashiori 
お疲れ様です。レビューしましたのでご確認をお願いします〜🙇‍♂️

ちなみに`.DS_Store`はコミットしなくて大丈夫です！
謎にステージに上がってた場合はファイルを削除して問題ないです！

2022-08-22 13:27 UTC, O-H-K-N commented on Gemfile.lock
> +  arm64-darwin-21
**107行目、108行目、198行目を削除しコミットしてから再度プッシュしてください。**
こちらは各メンバーごとのPCで環境が違うので、リモートでマージしてしまうと、各ローカルにプルしたときにコンフリクトが起こる可能性があります。
今後は、`Gemfile.lock`の変更はコミット、プッシュしないようにお願いします🙇‍♂️

2022-08-22 13:27 UTC, O-H-K-N commented on app/models/libraries_service.rb
> +  belongs_to :service
一応以下の設定を追加でお願いします。
```
# library_idとservice_idの組み合わせがuniqueであることを設定
validates :library_id, uniqueness: { scope: :service_id}
```

2022-08-22 13:27 UTC, O-H-K-N commented on db/migrate/20220821224140_create_libraries_services.rb
> +    end
このままでも大丈夫だと思いますが、8行目と9行目の間に以下のコードを入れて`rails db:migrate`し直してください。
```
# library_idとservice_idの組み合わせがuniqueであることを設定
add_index :libraries_services, [:library_id :service_id], unique: :true
```

※この設定がないと、図書館ID、サービスIDが同じ組み合わせのデータが登録されてしまいます

2022-08-25 09:09 UTC, isakashiori commented
@O-H-K-N 
お疲れ様です!
該当箇所を修正いたしました。ご確認お願いいたします!
修正:db/migrate/20220821224140にadd_indexを追加 https://github.com/O-H-K-N/tokyo-library-rails/pull/6/commits/6d25e325ec3e1a1123f0e3adcc837948e9d9408c

2022-08-25 09:37 UTC, O-H-K-N commented
@isakashiori 
https://github.com/O-H-K-N/tokyo-library-rails/pull/6#discussion_r951435098 ←こっちの修正もお願いします🙇‍♂️

2022-08-25 10:33 UTC, isakashiori commented
お疲れ様です。
何度もすみません....
修正完了しました。ご確認お願いします！

修正:libraries_service.rbにバリデーション追加 https://github.com/O-H-K-N/tokyo-library-rails/pull/6/commits/98ddf48e49e732dcf21a6b38884da197d4cd18b5

2022-08-25 10:36 UTC, O-H-K-N approved these changes
@isakashiori 
確認しました！
ありがとうございます！

2022-08-25 11:12 UTC, merged