add: sorceryによるUserテーブルの作成
O-H-K-N/tokyo-library-rails pull request #7
Opened 2022-08-23 08:52 UTC by tmtkzk0823

## 実装内容
gem sorceryを使って Userモデル作成しました。
テーブルの作成だけなのでバリデーション等はまだ追加していません。
ご確認お願いします。
c76220f0429c5efe3bf99dc9b19dc32128616c53

2022-08-23 10:31 UTC, O-H-K-N requested changes
コメントしました！
ご確認お願いします！

2022-08-23 10:31 UTC, O-H-K-N commented on app/models/user.rb
> +  authenticates_with_sorcery!
こちらUserのバリデーションも追加してもらって大丈夫だと思います！
以下参考です！
```
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
validates :email, presence: true validates :email, uniqueness: true, format: { with: VALID_EMAIL_REGEX }, allow_blank: true
validates :password, presence: true
validates :password, length: { in: 8..20 }, if: -> { new_record? || changes[:crypted_password] }, allow_blank: true
validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
```

2022-08-23 14:57 UTC, tmtkzk0823 commented
### 追加：Userモデルにバリデーションを追加
Userモデルにバリデーションを追加しました。
ご確認程、よろしくお願いします！
14627bc0fe5f208c4f28f4b8ab51aadc85de0981

2022-08-24 13:42 UTC, O-H-K-N approved these changes
変更確認しました！
ありがとうございます！

2022-08-25 03:05 UTC, tmtkzk0823 commented
### 追加：bookmarksテーブルの作成、及びバリデーション、アソシエーションの設定
4c3f21149b653a8af328a7752ee6b8bbc8b743e8
お気に入り機能として使う `Usersテーブル` と `librariesテーブル` の中間テーブルである`bookmarksテーブル`を作成しました。
また、追加に伴う各テーブルとのアソシエーション、バリデーションも追加しましたのでご確認お願いします！

2022-08-25 08:21 UTC, O-H-K-N requested changes
コメントしました！
確認お願いします！

2022-08-25 08:21 UTC, O-H-K-N commented on app/models/user.rb
> +  has_many :libraries, through: :bookmarks
一応`source`オプションをつけた形式にしておいてください。
また、オブジェクト名も「いいねしている図書館」てことでbookmark_librariesでお願いします。
```
has_many :bookmark_libraries, through: :bookmarks, source: :libraries
```

2022-08-25 08:21 UTC, O-H-K-N commented on app/models/library.rb
> +  has_many :users, through: :bookmarks
この1行は、一つの図書館に対してお気に入り登録しているすべてのユーザを参照することはないと思うので、無くてもいいかなと思います。

2022-08-25 10:45 UTC, tmtkzk0823 commented
## 修正：Userモデル、Libraryモデルのアソシエーションを修正
ご指摘いただいた必要のないアソシエーションの削除、souceオプションをつけたアソシエーションを追加いたしました！
ご確認お願いします！
8edbc6f27380f9f1089319c1e9cea8bfae8847f4

2022-08-25 10:52 UTC, O-H-K-N approved these changes
確認しました！
ありがとうございます！

2022-08-25 12:04 UTC, merged